arch:
- ppc64le
- s390x
language: php
dist: xenial

php:
- 7.1
- 7.2
- 7.3

# cache:
#   directories:
#    - /home/travis/.rvm/
     
# env:
# - BUILD=1
# - BUILD=2
# - BUILD=3

before_install:
- sudo rm -rf /var/lib/apt/lists/lock /var/cache/apt/archives/lock /var/lib/dpkg/lock
- sudo apt-get update
- sudo apt-get -y -q=2 --no-install-recommends --no-install-suggests libtidy-dev libxml2-dev libcurl4-openssl-dev libjpeg-dev libpng-dev libxpm-dev libmysqlclient-dev libpq-dev libicu-dev libfreetype6-dev libldap2-dev libxslt-dev libssl-dev libldb-dev libc-client-dev libkrb5-dev libsasl2-dev libmcrypt-dev expect
#install: skip

script:
# Environment information
- echo "==> Environment information"
- uname -a
- cat /etc/os-release
- grep ^processor /proc/cpuinfo
- free -m
- df -h

# Snaps
# - echo "==> Snaps"
# - sudo snap install core || true
# - sudo snap install core
# - sudo snap install hello-world
# - hello-world

# Sleep
#- sleep 600

# Docker
- echo "==> Docker"
- docker info
- docker run hello-world

# # # ruby
- echo "==> Ruby"
- ruby -v
#- gem i bundler
# # #- sleep 120

# # # python
- echo "==> Python"
- python -V

# # # php
- echo "==> PHP"
- php -V
